img_size:
- 640
- 640
model_name: yolov5m
test:
  conf_thresh: 0.35
  data_root: G:\dataset\yaogan\aircraft_100\test
  img_size: 640
  nms_thresh: 0.45
  weights_path: G:/dataset/yaogan/aircraft_100/train/outputs/final_200.pt
train:
  batch_size: 8
  data_root: G:\dataset\yaogan\aircraft_100\train
  mini_batch_size: 3
  num_epoch: 200
  num_worker: 0
  resolution: 1080
  save_interval: 50
  weights_path: ''
val:
  data_root: G:\dataset\yaogan\aircraft_100\val
