# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'yolo_ui_v2.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_YoloWindow(object):
    def setupUi(self, YoloWindow):
        YoloWindow.setObjectName("YoloWindow")
        YoloWindow.setEnabled(True)
        YoloWindow.resize(1022, 1065)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("ui/icon/ai.icon"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        YoloWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(YoloWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setObjectName("tabWidget")
        self.train_mode = QtWidgets.QWidget()
        self.train_mode.setObjectName("train_mode")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.train_mode)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_5 = QtWidgets.QLabel(self.train_mode)
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 8, 3, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.train_mode)
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("gui/ui/1.png"))
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 0, 0, 6, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.train_mode)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 0, 1, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.train_textBrowser = QtWidgets.QTextBrowser(self.train_mode)
        self.train_textBrowser.setObjectName("train_textBrowser")
        self.verticalLayout.addWidget(self.train_textBrowser)
        self.gridLayout.addLayout(self.verticalLayout, 11, 0, 1, 1)
        self.train_stop = QtWidgets.QPushButton(self.train_mode)
        self.train_stop.setMinimumSize(QtCore.QSize(0, 50))
        self.train_stop.setObjectName("train_stop")
        self.gridLayout.addWidget(self.train_stop, 3, 3, 3, 1)
        self.label = QtWidgets.QLabel(self.train_mode)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 2, 1, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(self.train_mode)
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout.addWidget(self.pushButton_4, 5, 1, 1, 1)
        self.train_start = QtWidgets.QPushButton(self.train_mode)
        self.train_start.setMinimumSize(QtCore.QSize(0, 50))
        self.train_start.setObjectName("train_start")
        self.gridLayout.addWidget(self.train_start, 0, 3, 2, 1)
        self.comboBox = QtWidgets.QComboBox(self.train_mode)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout.addWidget(self.comboBox, 3, 1, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.train_mode)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 1, 1, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.train_mode)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 6, 3, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.train_mode)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 6, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.train_mode)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 6, 0, 1, 1)
        self.gridLayout.setColumnStretch(0, 3)
        self.gridLayout_4.addLayout(self.gridLayout, 0, 1, 1, 1)
        self.tabWidget.addTab(self.train_mode, "")
        self.test_mode = QtWidgets.QWidget()
        self.test_mode.setObjectName("test_mode")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.test_mode)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.pushButton_3 = QtWidgets.QPushButton(self.test_mode)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout_5.addWidget(self.pushButton_3, 12, 1, 1, 1)
        self.test_video = QtWidgets.QPushButton(self.test_mode)
        self.test_video.setObjectName("test_video")
        self.gridLayout_5.addWidget(self.test_video, 11, 0, 1, 1)
        self.pushButton_stop = QtWidgets.QPushButton(self.test_mode)
        self.pushButton_stop.setObjectName("pushButton_stop")
        self.gridLayout_5.addWidget(self.pushButton_stop, 9, 1, 1, 1)
        self.test_ca = QtWidgets.QPushButton(self.test_mode)
        self.test_ca.setObjectName("test_ca")
        self.gridLayout_5.addWidget(self.test_ca, 12, 0, 1, 1)
        self.test_image = QtWidgets.QPushButton(self.test_mode)
        self.test_image.setObjectName("test_image")
        self.gridLayout_5.addWidget(self.test_image, 9, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.test_mode)
        self.label_9.setText("")
        self.label_9.setObjectName("label_9")
        self.gridLayout_5.addWidget(self.label_9, 13, 0, 1, 2)
        self.test_weights = QtWidgets.QPushButton(self.test_mode)
        self.test_weights.setObjectName("test_weights")
        self.gridLayout_5.addWidget(self.test_weights, 0, 0, 1, 2)
        self.label_8 = QtWidgets.QLabel(self.test_mode)
        self.label_8.setObjectName("label_8")
        self.gridLayout_5.addWidget(self.label_8, 6, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.test_mode)
        self.label_7.setObjectName("label_7")
        self.gridLayout_5.addWidget(self.label_7, 2, 0, 1, 1)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.test_mode)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout_5.addWidget(self.lineEdit_3, 6, 1, 1, 1)
        self.testmode = QtWidgets.QPushButton(self.test_mode)
        self.testmode.setObjectName("testmode")
        self.gridLayout_5.addWidget(self.testmode, 7, 0, 1, 2)
        self.test_dir = QtWidgets.QPushButton(self.test_mode)
        self.test_dir.setObjectName("test_dir")
        self.gridLayout_5.addWidget(self.test_dir, 8, 0, 1, 2)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.test_mode)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout_5.addWidget(self.lineEdit_2, 2, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.test_mode)
        self.label_3.setGeometry(QtCore.QRect(11, 279, 972, 681))
        self.label_3.setMaximumSize(QtCore.QSize(972, 16777215))
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.tabWidget.addTab(self.test_mode, "")
        self.gridLayout_3.addWidget(self.tabWidget, 0, 0, 1, 1)
        YoloWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(YoloWindow)
        self.statusbar.setObjectName("statusbar")
        YoloWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(YoloWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1022, 26))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        YoloWindow.setMenuBar(self.menubar)
        self.actionLabelImg = QtWidgets.QAction(YoloWindow)
        self.actionLabelImg.setObjectName("actionLabelImg")
        self.setting_action = QtWidgets.QAction(YoloWindow)
        self.setting_action.setObjectName("setting_action")
        self.actionxml_txt = QtWidgets.QAction(YoloWindow)
        self.actionxml_txt.setObjectName("actionxml_txt")
        self.actionpt_ncnn = QtWidgets.QAction(YoloWindow)
        self.actionpt_ncnn.setObjectName("actionpt_ncnn")
        self.action_resolution = QtWidgets.QAction(YoloWindow)
        self.action_resolution.setObjectName("action_resolution")
        self.action_2 = QtWidgets.QAction(YoloWindow)
        self.action_2.setObjectName("action_2")
        self.setting_action_2 = QtWidgets.QAction(YoloWindow)
        self.setting_action_2.setObjectName("setting_action_2")
        self.menu.addAction(self.actionLabelImg)
        self.menu.addAction(self.actionxml_txt)
        self.menu.addAction(self.actionpt_ncnn)
        self.menu.addSeparator()
        self.menu.addAction(self.action_2)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(YoloWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(YoloWindow)

    def retranslateUi(self, YoloWindow):
        _translate = QtCore.QCoreApplication.translate
        YoloWindow.setWindowTitle(_translate("YoloWindow", "目标检测训练器"))
        self.pushButton_2.setText(_translate("YoloWindow", "选择自训练模型(pt文件）"))
        self.train_stop.setText(_translate("YoloWindow", "停止"))
        self.label.setText(_translate("YoloWindow", "选择训练批次"))
        self.pushButton_4.setText(_translate("YoloWindow", "选择训练结果保存路径"))
        self.train_start.setText(_translate("YoloWindow", "开始"))
        self.comboBox.setItemText(0, _translate("YoloWindow", "1"))
        self.comboBox.setItemText(1, _translate("YoloWindow", "2"))
        self.comboBox.setItemText(2, _translate("YoloWindow", "3"))
        self.comboBox.setItemText(3, _translate("YoloWindow", "4"))
        self.comboBox.setItemText(4, _translate("YoloWindow", "5"))
        self.comboBox.setItemText(5, _translate("YoloWindow", "6"))
        self.comboBox.setItemText(6, _translate("YoloWindow", "7"))
        self.comboBox.setItemText(7, _translate("YoloWindow", "8"))
        self.comboBox.setItemText(8, _translate("YoloWindow", "9"))
        self.comboBox.setItemText(9, _translate("YoloWindow", "10"))
        self.comboBox.setItemText(10, _translate("YoloWindow", "11"))
        self.comboBox.setItemText(11, _translate("YoloWindow", "12"))
        self.pushButton.setText(_translate("YoloWindow", "选择训练数据(yaml文件)"))
        self.label_4.setText(_translate("YoloWindow", "最大迭代次数"))
        self.label_2.setText(_translate("YoloWindow", "训练进度：已训练次数/总次数"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.train_mode), _translate("YoloWindow", "训练模式"))
        self.pushButton_3.setText(_translate("YoloWindow", "结束检测"))
        self.test_video.setText(_translate("YoloWindow", "视频检测"))
        self.pushButton_stop.setText(_translate("YoloWindow", "暂停/继续"))
        self.test_ca.setText(_translate("YoloWindow", "摄像头检测"))
        self.test_image.setText(_translate("YoloWindow", "图片检测"))
        self.test_weights.setText(_translate("YoloWindow", "选择weights(pt文件)"))
        self.label_8.setText(_translate("YoloWindow", "nms的阈值，调小会减少重复框（默认0.45）                               "))
        self.label_7.setText(_translate("YoloWindow", "选择置信度（置信度的阈值，调低会增加预测框，但会降低准确率）默认0.4"))
        self.testmode.setText(_translate("YoloWindow", "初始化模型"))
        self.test_dir.setText(_translate("YoloWindow", "选择检测结果保存路径"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.test_mode), _translate("YoloWindow", "测试模式"))
        self.menu.setTitle(_translate("YoloWindow", "工具"))
        self.actionLabelImg.setText(_translate("YoloWindow", "LabelImg标注工具"))
        self.setting_action.setText(_translate("YoloWindow", "设置"))
        self.actionxml_txt.setText(_translate("YoloWindow", "标注格式转换工具"))
        self.actionpt_ncnn.setText(_translate("YoloWindow", "pt转PyToC工具"))
        self.action_resolution.setText(_translate("YoloWindow", "转换图片分辨率工具"))
        self.action_2.setText(_translate("YoloWindow", "关于"))
        self.setting_action_2.setText(_translate("YoloWindow", "设置"))
        self.setting_action_2.setToolTip(_translate("YoloWindow", "设置"))

